[verteilzentrum]
hostname = "localhost"
read_timeout = 10000
write_timeout = 10000
max_message_bytes = 1048576 # 1024 * 1024
tls_cert_file = "/some/path/cert.pem"
tls_key_file = "/some/path/key.pem"


[[list]]
name = "news@lists.example.com"
whitelist = ["hostmaster@example.com","john@example.com"]
blacklist = []
can_publish = ["*"]